version: '3'

tasks:
  run:
    desc: Start the Go project
    cmd: go run cmd/main.go
    
  oapi-gen:
    desc: Generates the API server code from the OpenAPI specification.
    cmds:
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest --config=./openapi/spec/server-conf.yaml ./openapi/spec/api.yaml
  
