package main

import (
	"log"
	"net/http"

	"bastienbyra.fr/bastienbyra/ByEmber/openapi/autogenerated"
	openapi "bastienbyra.fr/bastienbyra/ByEmber/openapi/server"
)

func main() {
	// create a type that satisfies the `api.ServerInterface`, which contains an implementation of every operation from the generated code
	server := openapi.NewServer()

	r := http.NewServeMux()

	// get an `http.Handler` that we can use
	h := autogenerated.HandlerFromMux(server, r)

	s := &http.Server{
		Handler: h,
		Addr:    "0.0.0.0:8080",
	}

	// And we serve HTTP until the world ends.
	log.Fatal(s.ListenAndServe())
}
