package openapi

import (
	"net/http"

	"bastienbyra.fr/bastienbyra/ByEmber/internal/secret"
	"bastienbyra.fr/bastienbyra/ByEmber/openapi/autogenerated"
	"github.com/google/uuid"
)

type Server struct {
	secretHandler *secret.SecretHandler
}

func NewServer() *Server {
	return &Server{
		secretHandler: secret.NewHandler(),
	}
}

var _ autogenerated.ServerInterface = (*Server)(nil)

func (s *Server) CreateSecret(w http.ResponseWriter, r *http.Request) {
	s.secretHandler.CreateSecret(w, r)
}

func (s *Server) DeleteSecret(w http.ResponseWriter, r *http.Request, id uuid.UUID) {
	s.secretHandler.DeleteSecret(w, r, id)
}

func (s *Server) GetSecret(w http.ResponseWriter, r *http.Request, id uuid.UUID) {
	s.secretHandler.GetSecret(w, r, id)
}
