package secret

import (
	"context"
	"database/sql"
	"fmt"

	"bastienbyra.fr/bastienbyra/ByEmber/openapi/autogenerated"
	"github.com/google/uuid"
)

type SecretRepository struct {
	db *sql.DB
}

func (r *SecretRepository) CreateSecret(ctx context.Context, s *autogenerated.Secret) error {
	query := `
		INSERT INTO secrets (id, content, created_at, duration, password, views)
		VALUES (?, ?, ?, ?, ?, ?)
	`

	fmt.Println(s.Content)
	_, err := r.db.ExecContext(ctx, query,
		s.Id.String(),
		s.Content,
		s.CreatedAt,
		s.Duration,
		s.Password,
		s.Views,
	)

	return err
}

func (r *SecretRepository) GetSecret(ctx context.Context, id string) (*autogenerated.Secret, error) {
	query := `
		SELECT id, content, created_at, duration, password, views
		FROM secrets
		WHERE id = ?
	`

	row := r.db.QueryRowContext(ctx, query, id)

	var s autogenerated.Secret
	var idStr string

	err := row.Scan(
		&idStr,
		&s.Content,
		&s.CreatedAt,
		&s.Duration,
		&s.Password,
		&s.Views,
	)

	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}

	parsedUUID, err := uuid.Parse(idStr)
	if err != nil {
		return nil, err
	}
	s.Id = &parsedUUID

	return &s, nil
}
