package secret

import (
	"context"
	"database/sql"
	"fmt"

	"bastienbyra.fr/bastienbyra/ByEmber/openapi/autogenerated"
)

type SecretRepository struct {
	db *sql.DB
}

func (r *SecretRepository) CreateSecret(ctx context.Context, s *autogenerated.Secret) error {
	query := `
		INSERT INTO secrets (id, content, created_at, duration, password, views)
		VALUES (?, ?, ?, ?, ?, ?)
	`

	fmt.Println(s.Content)
	_, err := r.db.ExecContext(ctx, query,
		s.Id.String(),
		s.Content,
		s.CreatedAt,
		s.Duration,
		s.Password,
		s.Views,
	)

	return err
}
