package secret

import (
	"crypto/sha256"
	"fmt"
	"time"

	"bastienbyra.fr/bastienbyra/ByEmber/openapi/autogenerated"
	"bastienbyra.fr/bastienbyra/ByEmber/utils"
	"github.com/google/uuid"
)

type SecretService struct {
	encyrptionService utils.EncryptionService
}

// func NewService() *SecretService {
// 	return &SecretService{}
// }

func (s *SecretService) CreateSecret(secretRequest autogenerated.SecretRequest) autogenerated.Secret {
	uuidValue := uuid.New()
	now := time.Now()

	encryptedContent, err := s.encyrptionService.Encrypt([]byte(secretRequest.Content))
	if err != nil {
		fmt.Println(err)
	}

	hash := sha256.Sum256([]byte(*secretRequest.Password))
	hashPassword := fmt.Sprintf("%x", hash)

	secret := autogenerated.Secret{
		Id:        &uuidValue,
		Content:   encryptedContent,
		CreatedAt: &now,
		Duration:  secretRequest.Duration,
		Password:  &hashPassword,
		Views:     secretRequest.Views,
	}

	return secret
}
